/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsoRockRouteImport } from './routes/aso-rock'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MethodRouteImport } from './routes/method'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as Results2023RouteImport } from './routes/results-2023'
import { Route as RumRouteImport } from './routes/rum'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsoRockRoute = AsoRockRouteImport.update({
  id: '/aso-rock',
  path: '/aso-rock',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsRoute = ElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const Results2023Route = Results2023RouteImport.update({
  id: '/results-2023',
  path: '/results-2023',
  getParentRoute: () => rootRouteImport,
} as any)
const RumRoute = RumRouteImport.update({
  id: '/rum',
  path: '/rum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aso-rock': typeof AsoRockRoute
  '/elections': typeof ElectionsRoute
  '/insights': typeof InsightsRoute
  '/method': typeof MethodRoute
  '/monitor': typeof MonitorRoute
  '/results-2023': typeof Results2023Route
  '/rum': typeof RumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aso-rock': typeof AsoRockRoute
  '/elections': typeof ElectionsRoute
  '/insights': typeof InsightsRoute
  '/method': typeof MethodRoute
  '/monitor': typeof MonitorRoute
  '/results-2023': typeof Results2023Route
  '/rum': typeof RumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aso-rock': typeof AsoRockRoute
  '/elections': typeof ElectionsRoute
  '/insights': typeof InsightsRoute
  '/method': typeof MethodRoute
  '/monitor': typeof MonitorRoute
  '/results-2023': typeof Results2023Route
  '/rum': typeof RumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aso-rock'
    | '/elections'
    | '/insights'
    | '/method'
    | '/monitor'
    | '/results-2023'
    | '/rum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aso-rock'
    | '/elections'
    | '/insights'
    | '/method'
    | '/monitor'
    | '/results-2023'
    | '/rum'
  id:
    | '__root__'
    | '/'
    | '/aso-rock'
    | '/elections'
    | '/insights'
    | '/method'
    | '/monitor'
    | '/results-2023'
    | '/rum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsoRockRoute: typeof AsoRockRoute
  ElectionsRoute: typeof ElectionsRoute
  InsightsRoute: typeof InsightsRoute
  MethodRoute: typeof MethodRoute
  MonitorRoute: typeof MonitorRoute
  Results2023Route: typeof Results2023Route
  RumRoute: typeof RumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aso-rock': {
      id: '/aso-rock'
      path: '/aso-rock'
      fullPath: '/aso-rock'
      preLoaderRoute: typeof AsoRockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results-2023': {
      id: '/results-2023'
      path: '/results-2023'
      fullPath: '/results-2023'
      preLoaderRoute: typeof Results2023RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rum': {
      id: '/rum'
      path: '/rum'
      fullPath: '/rum'
      preLoaderRoute: typeof RumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsoRockRoute: AsoRockRoute,
  ElectionsRoute: ElectionsRoute,
  InsightsRoute: InsightsRoute,
  MethodRoute: MethodRoute,
  MonitorRoute: MonitorRoute,
  Results2023Route: Results2023Route,
  RumRoute: RumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
