/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as RumRouteImport } from './routes/rum'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsRoute = ElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const RumRoute = RumRouteImport.update({
  id: '/rum',
  path: '/rum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/elections': typeof ElectionsRoute
  '/monitor': typeof MonitorRoute
  '/rum': typeof RumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/elections': typeof ElectionsRoute
  '/monitor': typeof MonitorRoute
  '/rum': typeof RumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/elections': typeof ElectionsRoute
  '/monitor': typeof MonitorRoute
  '/rum': typeof RumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/elections' | '/monitor' | '/rum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/elections' | '/monitor' | '/rum'
  id: '__root__' | '/' | '/elections' | '/monitor' | '/rum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElectionsRoute: typeof ElectionsRoute
  MonitorRoute: typeof MonitorRoute
  RumRoute: typeof RumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rum': {
      id: '/rum'
      path: '/rum'
      fullPath: '/rum'
      preLoaderRoute: typeof RumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElectionsRoute: ElectionsRoute,
  MonitorRoute: MonitorRoute,
  RumRoute: RumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
